#version: "3.9"

services:
  processor:
    build: ./processor-service
    container_name: processor
    ports:
      - "9190:9090"        # host 9190 → container 9090
    volumes:
      - ./logs/processor:/app/logs
    networks:
      - app_net

  handler:
    build: ./handler-service
    container_name: handler
    environment:
      - PROCESSOR_URL=http://processor:9090/process
    ports:
      - "9191:9091"        # host 9191 → container 9091
    volumes:
      - ./logs/handler:/app/logs
    depends_on:
      - processor
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9095:9090"        # host 9095 → container 9090
    networks:
      - app_net
    depends_on:
      - handler
      - processor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"        # host 3000 → container 3000
    networks:
      - app_net
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic-generator
    depends_on:
      - handler
    networks:
      - app_net
  
  fluentbit:
    image: fluent/fluent-bit:2.1
    container_name: fluentbit
    volumes:
      - ./logs:/var/log/myapp
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - handler
      - processor
      - elasticsearch
    networks:
      - app_net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - app_net
    depends_on:
      - elasticsearch
networks:
  app_net:
    driver: bridge