apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"
      containers:
      - name: traffic-generator
        image: curlimages/curl:8.5.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "🚀 Starting traffic generator...";
            while true; do
              AMOUNT=$(( (RANDOM % 3000) + 100 ));
              RESPONSE=$(curl -s -X POST http://handler-service:9091/api/v1/transactions \
                -H "Content-Type: application/json" \
                -d "{\"amount\": $AMOUNT, \"currency\": \"EUR\", \"merchantId\": \"M123\"}");
              echo "[TrafficGen] Sent txn amount=$AMOUNT → Response: $RESPONSE";
              sleep 5;
            done